# Generated by Django 5.2.16 on 2026-08-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimBusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveBigIntegerField(unique=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('quarter', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FactApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveBigIntegerField(unique=True)),
                ('application_type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('accepted', models.BooleanField(default=False)),
                ('processing_days', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics.dimbusinessunit')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.dimdate')),
            ],
        ),
        migrations.CreateModel(
            name='FactTrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveBigIntegerField(unique=True)),
                ('status', models.CharField(max_length=32)),
                ('completed', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics.dimbusinessunit')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.dimdate')),
            ],
        ),
    ]
