# Generated by Django 5.2.16 on 2026-07-14 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'BU_MANAGER'}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_business_units', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessUnitNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du besoin')),
                ('description', models.TextField(verbose_name='Description')),
                ('need_type', models.CharField(choices=[('HIRING', 'Recrutement'), ('INTERNSHIP', 'Stage'), ('FREELANCE', 'Freelance')], default='HIRING', max_length=50, verbose_name='Type de besoin')),
                ('required_skills', models.TextField(blank=True, verbose_name='Compétences requises')),
                ('required_level', models.CharField(choices=[('JUNIOR', 'Junior (0-2 ans)'), ('MID', 'Intermédiaire (3-5 ans)'), ('SENIOR', 'Senior (5+ ans)'), ('EXPERT', 'Expert')], default='MID', max_length=50, verbose_name='Niveau requis')),
                ('number_of_profiles', models.PositiveIntegerField(default=1, verbose_name='Nombre de profils')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=50, verbose_name='Priorité')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Date attendue')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('FULFILLED', 'Pourvu'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=50, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='business_units.businessunit', verbose_name='Business Unit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bu_needs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Besoin de Business Unit',
                'verbose_name_plural': 'Besoins de Business Unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessUnitMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Poste')),
                ('joined_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date de rejoindre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='business_units.businessunit', verbose_name='Business Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bu_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre de Business Unit',
                'verbose_name_plural': 'Membres de Business Unit',
                'ordering': ['-joined_at'],
                'unique_together': {('business_unit', 'user')},
            },
        ),
    ]
