# Generated by Django 5.2.16 on 2026-07-14 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessunitmembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='businessunitmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('business_unit', 'user'), name='unique_active_bu_membership'),
        ),
    ]
