# Generated by Django 5.2.16 on 2026-07-15 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_need_types(apps, schema_editor):
    BusinessUnitNeed = apps.get_model('business_units', 'BusinessUnitNeed')
    BusinessUnitNeed.objects.filter(need_type__in=['HIRING', 'INTERNSHIP']).update(
        need_type='RECRUITMENT_INTERNSHIP'
    )
    BusinessUnitNeed.objects.filter(need_type='FREELANCE').update(need_type='OTHER')


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0002_alter_businessunitmembership_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunitneed',
            name='concerned_collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_unit_needs', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateur concerné'),
        ),
        migrations.AddField(
            model_name='businessunitneed',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TRAINER_TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bu_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Formateur'),
        ),
        migrations.AddField(
            model_name='businessunitneed',
            name='training_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de la formation'),
        ),
        migrations.AddField(
            model_name='businessunitneed',
            name='training_link',
            field=models.URLField(blank=True, verbose_name='Lien de la formation'),
        ),
        migrations.AddField(
            model_name='businessunitneed',
            name='training_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Début de la formation'),
        ),
        migrations.RunPython(normalize_need_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='businessunitneed',
            name='need_type',
            field=models.CharField(choices=[('RECRUITMENT_INTERNSHIP', 'Recrutement / stagiaire'), ('TRAINING', 'Formation'), ('OTHER', 'Autre')], default='RECRUITMENT_INTERNSHIP', max_length=50, verbose_name='Type de besoin'),
        ),
        migrations.AlterField(
            model_name='businessunitneed',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('VALIDATED', 'Validé'), ('FULFILLED', 'Pourvu'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=50, verbose_name='Statut'),
        ),
    ]
