# Generated by Django 5.2.16 on 2026-07-15 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_workflow_statuses(apps, schema_editor):
    BusinessUnitNeed = apps.get_model('business_units', 'BusinessUnitNeed')
    BusinessUnitNeed.objects.filter(status__in=['DRAFT', 'OPEN', 'IN_PROGRESS']).update(status='SUBMITTED')
    BusinessUnitNeed.objects.filter(status__in=['VALIDATED', 'FULFILLED']).update(status='CONFIRMED')
    BusinessUnitNeed.objects.filter(status='CANCELLED').update(status='REFUSED')


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0003_businessunitneed_concerned_collaborator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessunitneed',
            old_name='concerned_collaborator',
            new_name='requester',
        ),
        migrations.AddField(
            model_name='businessunitneed',
            name='decision_comment',
            field=models.TextField(blank=True, verbose_name='Commentaire de décision'),
        ),
        migrations.AlterField(
            model_name='businessunitneed',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_business_unit_needs', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur'),
        ),
        migrations.AddField(
            model_name='businessunitneed',
            name='training_audience',
            field=models.CharField(choices=[('ALL', 'Tous les collaborateurs de la BU'), ('SPECIFIC', 'Collaborateurs spécifiques')], default='ALL', max_length=20, verbose_name='Public cible'),
        ),
        migrations.AddField(
            model_name='businessunitneed',
            name='training_recipients',
            field=models.ManyToManyField(blank=True, related_name='targeted_bu_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateurs ciblés'),
        ),
        migrations.RunPython(normalize_workflow_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='businessunitneed',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Soumis'), ('CONFIRMED', 'Confirmé'), ('REFUSED', 'Refusé'), ('DRAFT', 'Brouillon'), ('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('VALIDATED', 'Validé'), ('FULFILLED', 'Pourvu'), ('CANCELLED', 'Annulé')], default='SUBMITTED', max_length=50, verbose_name='Statut'),
        ),
    ]
