# Generated by Django 5.2.16 on 2026-07-15 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0004_remove_businessunitneed_concerned_collaborator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunitmembership',
            name='joined_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de rejoindre'),
        ),
    ]
