# Generated by Django 5.2.16 on 2026-07-16 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0005_alter_businessunitmembership_joined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunitneed',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('UNDER_REVIEW', "En cours d'examen"), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('SATISFIED', 'Satisfait'), ('CLOSED', 'Clôturé')], default='SUBMITTED', max_length=50, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='BusinessUnitNeedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=50, verbose_name='Statut précédent')),
                ('to_status', models.CharField(max_length=50, verbose_name='Nouveau statut')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='business_units.businessunitneed', verbose_name='Besoin')),
            ],
            options={
                'verbose_name': 'Historique du besoin',
                'verbose_name_plural': 'Historiques des besoins',
                'ordering': ['-created_at'],
            },
        ),
    ]
