# Generated by Django 5.2.16 on 2026-07-28 15:00
from django.db import migrations

def migrate_statuses(apps, schema_editor):
    BusinessUnitNeed = apps.get_model('business_units', 'BusinessUnitNeed')
    BusinessUnitNeedHistory = apps.get_model('business_units', 'BusinessUnitNeedHistory')

    # Update BusinessUnitNeed
    BusinessUnitNeed.objects.filter(status='CONFIRMED').update(status='ACCEPTED')
    BusinessUnitNeed.objects.filter(status='REFUSED').update(status='REJECTED')

    # Update BusinessUnitNeedHistory
    BusinessUnitNeedHistory.objects.filter(from_status='CONFIRMED').update(from_status='ACCEPTED')
    BusinessUnitNeedHistory.objects.filter(from_status='REFUSED').update(from_status='REJECTED')
    BusinessUnitNeedHistory.objects.filter(to_status='CONFIRMED').update(to_status='ACCEPTED')
    BusinessUnitNeedHistory.objects.filter(to_status='REFUSED').update(to_status='REJECTED')

def reverse_migrate_statuses(apps, schema_editor):
    BusinessUnitNeed = apps.get_model('business_units', 'BusinessUnitNeed')
    BusinessUnitNeedHistory = apps.get_model('business_units', 'BusinessUnitNeedHistory')

    BusinessUnitNeed.objects.filter(status='ACCEPTED').update(status='CONFIRMED')
    BusinessUnitNeed.objects.filter(status='REJECTED').update(status='REFUSED')

    BusinessUnitNeedHistory.objects.filter(from_status='ACCEPTED').update(from_status='CONFIRMED')
    BusinessUnitNeedHistory.objects.filter(from_status='REJECTED').update(from_status='REFUSED')
    BusinessUnitNeedHistory.objects.filter(to_status='ACCEPTED').update(to_status='CONFIRMED')
    BusinessUnitNeedHistory.objects.filter(to_status='REJECTED').update(to_status='REFUSED')


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0006_alter_businessunitneed_status_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_migrate_statuses),
    ]
