# Generated by Django 5.2.16 on 2026-07-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0007_migrate_obsolete_need_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunitneed',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('UNDER_REVIEW', "En cours d'examen"), ('ACCEPTED', 'Approuvé'), ('REJECTED', 'Refusé'), ('SATISFIED', 'Satisfait'), ('CLOSED', 'Clôturé')], default='SUBMITTED', max_length=50, verbose_name='Statut'),
        ),
    ]
