# Generated by Django 5.2.16 on 2026-08-06 08:48

from django.db import migrations, models


CANONICAL = ("NetSEC", "System", "Software", "Achat")


def clean_business_units(apps, schema_editor):
    BusinessUnit = apps.get_model("business_units", "BusinessUnit")
    Membership = apps.get_model("business_units", "BusinessUnitMembership")
    User = apps.get_model("accounts", "User")

    manager = User.objects.filter(role="BU_MANAGER").order_by("pk").first()
    canonical_by_code = {}
    for code in CANONICAL:
        unit = BusinessUnit.objects.filter(code__iexact=code).order_by("pk").first()
        if unit:
            unit.code = code
            unit.name = code
            unit.save(update_fields=["code", "name"])
        elif manager:
            unit = BusinessUnit.objects.create(name=code, code=code, manager_id=manager.pk)
        if unit:
            canonical_by_code[code] = unit

    # BI and every other legacy department are consolidated into Software so
    # related business records are preserved before the obsolete row is removed.
    target = canonical_by_code.get("Software")
    for legacy in BusinessUnit.objects.exclude(code__in=CANONICAL).order_by("pk"):
        if target is None:
            legacy.name = "Software"
            legacy.code = "Software"
            legacy.save(update_fields=["name", "code"])
            target = legacy
            canonical_by_code["Software"] = legacy
            continue

        duplicate_users = Membership.objects.filter(business_unit=target).values_list("user_id", flat=True)
        Membership.objects.filter(
            business_unit=legacy, user_id__in=duplicate_users
        ).delete()
        for relation in legacy._meta.related_objects:
            related_model = relation.related_model
            field_name = relation.field.name
            related_model.objects.filter(**{field_name: legacy}).update(**{field_name: target})
        legacy.delete()


def noop_reverse(apps, schema_editor):
    # Removing legacy departments is intentionally irreversible.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0008_alter_businessunitneed_status'),
    ]

    operations = [
        migrations.RunPython(clean_business_units, noop_reverse),
        migrations.AlterField(
            model_name='businessunit',
            name='code',
            field=models.CharField(choices=[('NetSEC', 'NetSEC'), ('System', 'System'), ('Software', 'Software'), ('Achat', 'Achat')], max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
