# Generated by Django 5.2.16 on 2026-08-06 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0009_alter_businessunit_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'BU_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_business_units', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
    ]
