# Generated by Django 5.2.16 on 2026-08-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0012_seed_default_business_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
