export const SUPPORTED_LANGUAGES = ['fr', 'en'] as const;
export type AppLanguage = (typeof SUPPORTED_LANGUAGES)[number];
export type TranslationParams = Record<string, string | number>;

const fr: Record<string, string> = {
  'nav.myCv':'Mon CV',
  'language.updateFailed':'La langue n’a pas pu être enregistrée. La langue précédente a été restaurée.',
  'language.fr':'Français','language.en':'Anglais',
  'common.loading':'Chargement…','common.save':'Enregistrer','common.cancel':'Annuler','common.confirm':'Confirmer','common.close':'Fermer','common.search':'Rechercher','common.actions':'Actions','common.status':'Statut','common.all':'Tous','common.none':'Aucun','common.notAssigned':'Non affecté','common.error':'Une erreur est survenue.','common.apply':'Appliquer','common.from':'Du','common.to':'Au','common.viewAll':'Voir tout','common.noData':'Aucune donnée disponible.',
  'validation.required':'Ce champ est obligatoire.','validation.email':'Adresse email invalide.','validation.passwordMin':'Le mot de passe doit contenir au moins 8 caractères.','validation.invalidFile':'Le fichier sélectionné est invalide.',
  'api.invalidCredentials':'Email ou mot de passe incorrect.','api.permissionDenied':'Vous n’avez pas les permissions nécessaires.','api.serverUnavailable':'Impossible de joindre le serveur. Vérifiez qu’il est bien démarré.','api.timeout':'Le serveur ne répond pas. Réessayez dans un instant.','api.emailExists':'Cette adresse email est déjà utilisée.','api.sessionExpired':'Votre session a expiré. Veuillez vous reconnecter.','api.requestFailed':'La requête a échoué. Réessayez dans un instant.',
  'auth.title':'Accéder à mon espace','auth.subtitle':'Connectez-vous avec les identifiants associés à votre profil.','auth.email':'Email','auth.emailPlaceholder':'votre.email@exemple.com','auth.password':'Mot de passe','auth.passwordPlaceholder':'Votre mot de passe','auth.togglePassword':'Afficher ou masquer le mot de passe','auth.login':'Se connecter','auth.loggingIn':'Connexion en cours…','auth.joinPrompt':'Vous souhaitez rejoindre Finatech ?','auth.apply':'Déposer une candidature',
  'nav.notifications':'Notifications','nav.reports':'Rapports & KPI','nav.auditLogs':'Journaux d’audit','nav.tools':'Outils','nav.trainingCatalog':'Catalogue des formations','nav.trainingParticipants':'Personnes inscrites','nav.overview':'Vue d’ensemble','nav.dashboard':'Tableau de bord','nav.recruitment':'Recrutement','nav.offers':'Offres','nav.applications':'Candidatures','nav.organization':'Organisation','nav.users':'Gestion des utilisateurs','nav.businessUnits':'Business Units','nav.buNeeds':'Besoins des BU','nav.myBuNeeds':'Besoins de ma BU','nav.myBuMembers':'Membres de ma BU','nav.myBuTrainings':'Formations de ma BU','nav.training':'Formation','nav.catalog':'Catalogue et sessions','nav.enrollments':'Inscriptions et validations','nav.attendance':'Présences et certificats','nav.clientTrainings':'Mes formations client','nav.internships':'Stages','nav.internManagement':'Gestion des stagiaires','nav.acceptedInterns':'Stagiaires acceptés','nav.collaboratorsByBu':'Collaborateurs par BU','nav.myInternship':'Mon stage','nav.projects':'Projets',
  'header.workspace':'Espace de travail','header.notifications':'Notifications','header.profile':'Mon profil','header.logout':'Déconnexion','header.language':'Langue','header.accountMenu':'Ouvrir le menu du compte',
  'role.SUPER_ADMIN':'Super administrateur','role.HR':'Ressources humaines','role.BU_MANAGER':'Manager BU','role.TRAINER_TUTOR':'Formateur','role.EMPLOYEE':'Collaborateur','role.INTERN':'Stagiaire','role.CANDIDATE':'Candidat','role.CLIENT':'Client externe',
  'dashboard.greeting':'Bonjour {{name}}','dashboard.welcome':'Bienvenue dans votre espace {{role}}.','dashboard.analysisPeriod':'Période d’analyse','dashboard.consolidated':'Données consolidées','dashboard.filters':'Filtres analytiques','dashboard.businessUnit':'Business Unit','dashboard.applicationStatus':'Statut candidature','dashboard.trainingType':'Type de formation','dashboard.totalApplications':'Total des candidatures','dashboard.activeInterns':'Stagiaires actifs','dashboard.activeEmployees':'Collaborateurs actifs','dashboard.openNeeds':'Besoins BU ouverts','dashboard.activeOffers':'Offres actives','dashboard.pendingApplications':'Candidatures en attente','dashboard.upcomingSessions':'Sessions à venir','dashboard.certificatesIssued':'Certificats délivrés','dashboard.monthlyApplications':'Évolution mensuelle des candidatures','dashboard.recentApplications':'Candidatures récentes','dashboard.statusDistribution':'Répartition des statuts','dashboard.internshipEvolution':'Évolution des stages par mois','dashboard.workforceByBu':'Répartition des effectifs par Business Unit','dashboard.trainingSummary':'Résumé des formations','dashboard.trainingsPlanned':'Formations planifiées','dashboard.registrations':'Inscriptions','dashboard.validatedAttendance':'Présences validées','dashboard.insights':'Insights opérationnels','dashboard.noInsights':'Aucune alerte notable pour les filtres sélectionnés.','dashboard.quickActions':'Actions rapides','dashboard.adminShortcuts':'Raccourcis administrateur','dashboard.candidate':'Candidat','dashboard.offer':'Offre','dashboard.date':'Date',
  'training.internal':'Interne','training.external':'Externe','training.upcomingSessions':'Sessions à venir',
  'profile.title':'Mon profil','profile.subtitle':'Gérez vos coordonnées et la sécurité de votre compte.','profile.firstName':'Prénom','profile.lastName':'Nom','profile.notProvided':'Non renseigné','profile.contact':'Coordonnées','profile.currentRequired':'Le mot de passe actuel est obligatoire.','profile.emailInvalid':'Adresse email invalide','profile.phone':'Téléphone','profile.phoneInvalid':'Numéro invalide','profile.currentPassword':'Mot de passe actuel','profile.required':'Champ obligatoire','profile.saveContact':'Enregistrer les coordonnées','profile.contactSaved':'Coordonnées mises à jour.','profile.password':'Mot de passe','profile.sessionClosed':'Votre session sera fermée après la modification.','profile.newPassword':'Nouveau mot de passe','profile.minLength':'8 caractères minimum','profile.confirmation':'Confirmation','profile.changePassword':'Modifier le mot de passe','profile.confirmChange':'Modifier votre mot de passe et fermer votre session ?','profile.mismatch':'Les nouveaux mots de passe ne correspondent pas.','profile.failed':'Modification impossible.',
  'intern.identity':'Identité','intern.manager':'Manager BU','intern.supervisor':'Encadrant','intern.start':'Début','intern.end':'Fin','intern.remaining':'Jours restants','intern.documentsValidated':'Documents validés','intern.progress':'Progression','intern.view':'Consulter mon stage','intern.unassigned':'Non affecté',
  'candidate.personal':'Informations personnelles','candidate.status':'Statut','candidate.offer':'Offre concernée','candidate.reference':'Référence','candidate.date':'Date de candidature',
  'public.home':'Accueil','public.group':'Le Groupe','public.expertise':'Nos expertises','public.offers':'Offres','public.contact':'Contact','public.apply':'Postuler','public.personalSpace':'Espace personnel','public.digitalPortal':'Portail digital','public.menuOpen':'Ouvrir le menu','public.footerDescription':'Portail digital dédié aux talents, aux formations et à la collaboration.','public.discover':'Découvrir','public.quickAccess':'Accès rapides','public.trackApplication':'Suivre ma candidature','public.employeeSpace':'Espace collaborateur','public.trainerSpace':'Espace formateur','public.clientSpace':'Espace client','public.privacy':'Confidentialité','public.dataProtection':'Protection des données','public.legal':'Mentions légales',
  'chat.sources':'Sources','chat.stop':'Arrêter la génération','chat.thinking':'L’assistant réfléchit…','chat.available':'Assistant disponible','chat.unavailable':'Assistant indisponible','chat.checking':'Vérification…','chat.title':'Assistant Smart Academy','chat.placeholder':'Posez votre question…','chat.send':'Envoyer','chat.new':'Nouvelle conversation','chat.unknown':'Je ne dispose pas de cette information.','chat.readOnly':'Lecture seule','chat.history':'Historique','chat.noHistory':'Aucune conversation.','chat.welcome':'Posez une question sur les données auxquelles vous avez accès.','chat.retry':'Réessayer','chat.ollamaUnavailable':'Ollama est arrêté ou inaccessible.','chat.modelUnavailable':'Le modèle Ollama configuré n’est pas installé.','chat.backendUnavailable':'Le backend du chatbot est inaccessible.'
};

const en: Record<string, string> = {
  'nav.myCv':'My CV',
  'language.updateFailed':'The language could not be saved. The previous language has been restored.',
  'language.fr':'French','language.en':'English',
  'common.loading':'Loading…','common.save':'Save','common.cancel':'Cancel','common.confirm':'Confirm','common.close':'Close','common.search':'Search','common.actions':'Actions','common.status':'Status','common.all':'All','common.none':'None','common.notAssigned':'Not assigned','common.error':'An error occurred.','common.apply':'Apply','common.from':'From','common.to':'To','common.viewAll':'View all','common.noData':'No data available.',
  'validation.required':'This field is required.','validation.email':'Invalid email address.','validation.passwordMin':'Password must contain at least 8 characters.','validation.invalidFile':'The selected file is invalid.',
  'api.invalidCredentials':'Incorrect email or password.','api.permissionDenied':'You do not have the required permission.','api.serverUnavailable':'Unable to reach the server. Make sure it is running.','api.timeout':'The server is not responding. Please try again shortly.','api.emailExists':'This email address is already in use.','api.sessionExpired':'Your session has expired. Please sign in again.','api.requestFailed':'The request failed. Please try again shortly.',
  'auth.title':'Access my workspace','auth.subtitle':'Sign in with the credentials associated with your profile.','auth.email':'Email','auth.emailPlaceholder':'your.email@example.com','auth.password':'Password','auth.passwordPlaceholder':'Your password','auth.togglePassword':'Show or hide password','auth.login':'Sign in','auth.loggingIn':'Signing in…','auth.joinPrompt':'Would you like to join Finatech?','auth.apply':'Submit an application',
  'nav.notifications':'Notifications','nav.reports':'Reports & KPI','nav.auditLogs':'Audit logs','nav.tools':'Tools','nav.trainingCatalog':'Training catalog','nav.trainingParticipants':'Enrolled people','nav.overview':'Overview','nav.dashboard':'Dashboard','nav.recruitment':'Recruitment','nav.offers':'Offers','nav.applications':'Applications','nav.organization':'Organization','nav.users':'User management','nav.businessUnits':'Business Units','nav.buNeeds':'BU needs','nav.myBuNeeds':'My BU needs','nav.myBuMembers':'My BU members','nav.myBuTrainings':'My BU training','nav.training':'Training','nav.catalog':'Catalog and sessions','nav.enrollments':'Enrollments and approvals','nav.attendance':'Attendance and certificates','nav.clientTrainings':'My client training','nav.internships':'Internships','nav.internManagement':'Intern management','nav.acceptedInterns':'Accepted interns','nav.collaboratorsByBu':'Employees by BU','nav.myInternship':'My internship','nav.projects':'Projects',
  'header.workspace':'Workspace','header.notifications':'Notifications','header.profile':'My profile','header.logout':'Sign out','header.language':'Language','header.accountMenu':'Open account menu',
  'role.SUPER_ADMIN':'Super Admin','role.HR':'Human Resources','role.BU_MANAGER':'BU Manager','role.TRAINER_TUTOR':'Trainer','role.EMPLOYEE':'Employee','role.INTERN':'Intern','role.CANDIDATE':'Candidate','role.CLIENT':'External client',
  'dashboard.greeting':'Hello {{name}}','dashboard.welcome':'Welcome to your {{role}} workspace.','dashboard.analysisPeriod':'Analysis period','dashboard.consolidated':'Consolidated data','dashboard.filters':'Analytics filters','dashboard.businessUnit':'Business Unit','dashboard.applicationStatus':'Application status','dashboard.trainingType':'Training type','dashboard.totalApplications':'Total applications','dashboard.activeInterns':'Active interns','dashboard.activeEmployees':'Active employees','dashboard.openNeeds':'Open BU needs','dashboard.activeOffers':'Active offers','dashboard.pendingApplications':'Pending applications','dashboard.upcomingSessions':'Upcoming sessions','dashboard.certificatesIssued':'Certificates issued','dashboard.monthlyApplications':'Monthly application trend','dashboard.recentApplications':'Recent applications','dashboard.statusDistribution':'Status distribution','dashboard.internshipEvolution':'Monthly internship trend','dashboard.workforceByBu':'Workforce by Business Unit','dashboard.trainingSummary':'Training summary','dashboard.trainingsPlanned':'Planned trainings','dashboard.registrations':'Registrations','dashboard.validatedAttendance':'Validated attendance','dashboard.insights':'Operational insights','dashboard.noInsights':'No notable alerts for the selected filters.','dashboard.quickActions':'Quick actions','dashboard.adminShortcuts':'Administrator shortcuts','dashboard.candidate':'Candidate','dashboard.offer':'Offer','dashboard.date':'Date',
  'training.internal':'Internal','training.external':'External','training.upcomingSessions':'Upcoming sessions',
  'profile.title':'My profile','profile.subtitle':'Manage your contact details and account security.','profile.firstName':'First name','profile.lastName':'Last name','profile.notProvided':'Not provided','profile.contact':'Contact details','profile.currentRequired':'Your current password is required.','profile.emailInvalid':'Invalid email address','profile.phone':'Phone','profile.phoneInvalid':'Invalid phone number','profile.currentPassword':'Current password','profile.required':'Required field','profile.saveContact':'Save contact details','profile.contactSaved':'Contact details updated.','profile.password':'Password','profile.sessionClosed':'Your session will close after the change.','profile.newPassword':'New password','profile.minLength':'At least 8 characters','profile.confirmation':'Confirmation','profile.changePassword':'Change password','profile.confirmChange':'Change your password and close your session?','profile.mismatch':'The new passwords do not match.','profile.failed':'Update failed.',
  'intern.identity':'Identity','intern.manager':'BU Manager','intern.supervisor':'Supervisor','intern.start':'Start','intern.end':'End','intern.remaining':'Days remaining','intern.documentsValidated':'Documents validated','intern.progress':'Progress','intern.view':'View my internship','intern.unassigned':'Not assigned',
  'candidate.personal':'Personal information','candidate.status':'Status','candidate.offer':'Related offer','candidate.reference':'Reference','candidate.date':'Application date',
  'public.home':'Home','public.group':'The Group','public.expertise':'Our expertise','public.offers':'Offers','public.contact':'Contact','public.apply':'Apply','public.personalSpace':'Personal workspace','public.digitalPortal':'Digital portal','public.menuOpen':'Open menu','public.footerDescription':'A digital portal dedicated to talent, training, and collaboration.','public.discover':'Discover','public.quickAccess':'Quick access','public.trackApplication':'Track my application','public.employeeSpace':'Employee workspace','public.trainerSpace':'Trainer workspace','public.clientSpace':'Client workspace','public.privacy':'Privacy','public.dataProtection':'Data protection','public.legal':'Legal notice',
  'chat.sources':'Sources','chat.stop':'Stop generation','chat.thinking':'The assistant is thinking…','chat.available':'Assistant available','chat.unavailable':'Assistant unavailable','chat.checking':'Checking…','chat.title':'Smart Academy Assistant','chat.placeholder':'Ask your question…','chat.send':'Send','chat.new':'New conversation','chat.unknown':'I do not have this information.','chat.readOnly':'Read only','chat.history':'History','chat.noHistory':'No conversations.','chat.welcome':'Ask about the data you are allowed to access.','chat.retry':'Retry','chat.ollamaUnavailable':'Ollama is stopped or unreachable.','chat.modelUnavailable':'The configured Ollama model is not installed.','chat.backendUnavailable':'The chatbot backend is unreachable.'
};

export const TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {fr, en};
