# Generated by Django 5.2.16 on 2026-07-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='study_field',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('CV', 'CV'), ('COVER_LETTER', 'Lettre de motivation'), ('PERSONAL_PHOTO', 'Photo personnelle'), ('OTHER', 'Autre piece')], max_length=32),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_school',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education_level',
            field=models.CharField(choices=[('FIRST_YEAR', '1re annee'), ('SECOND_YEAR', '2e annee'), ('THIRD_YEAR', '3e annee'), ('FOURTH_YEAR', '4e annee'), ('FIFTH_YEAR', '5e annee'), ('BACHELOR', 'Licence'), ('MASTER', 'Master'), ('ENGINEERING', 'Cycle ingenieur'), ('DOCTORATE', 'Doctorat'), ('OTHER', 'Autre')], max_length=32),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(max_length=32),
        ),
    ]
