# Generated by Django 5.2.16 on 2026-07-16 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0006_alter_businessunitneed_status_and_more'),
        ('recruitment', '0003_rename_education_level_study_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Reçue'), ('UNDER_REVIEW', "En cours d'étude"), ('PRESELECTED', 'Présélectionné'), ('INTERVIEW', 'Entretien'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('ARCHIVED', 'Archivé')], default='RECEIVED', max_length=32),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('RECEIVED', 'Reçue'), ('UNDER_REVIEW', "En cours d'étude"), ('PRESELECTED', 'Présélectionné'), ('INTERVIEW', 'Entretien'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('ARCHIVED', 'Archivé')], max_length=32),
        ),
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='to_status',
            field=models.CharField(choices=[('RECEIVED', 'Reçue'), ('UNDER_REVIEW', "En cours d'étude"), ('PRESELECTED', 'Présélectionné'), ('INTERVIEW', 'Entretien'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('ARCHIVED', 'Archivé')], max_length=32),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('application_type', models.CharField(choices=[('PFA_INTERNSHIP', 'Stage PFA'), ('PFE_INTERNSHIP', 'Stage PFE'), ('HIRING', 'Candidature pour embauche')], max_length=32, verbose_name="Type d'offre")),
                ('required_skills', models.TextField(blank=True)),
                ('required_level', models.CharField(blank=True, choices=[('FIRST_YEAR', '1re annee'), ('SECOND_YEAR', '2e annee'), ('THIRD_YEAR', '3e annee'), ('FOURTH_YEAR', '4e annee'), ('FIFTH_YEAR', '5e annee'), ('BACHELOR', 'Licence'), ('MASTER', 'Master'), ('ENGINEERING', 'Cycle ingenieur'), ('DOCTORATE', 'Doctorat'), ('OTHER', 'Autre')], max_length=32)),
                ('number_of_positions', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publiée'), ('CLOSED', 'Fermée'), ('ARCHIVED', 'Archivée')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='business_units.businessunit')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='recruitment.offer'),
        ),
    ]
