# Generated by Django 5.2.16 on 2026-07-16 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_units', '0006_alter_businessunitneed_status_and_more'),
        ('recruitment', '0004_alter_application_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to='business_units.businessunit'),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='current_status',
            field=models.CharField(choices=[('UPCOMING', 'À venir'), ('ACTIVE', 'En cours'), ('SUSPENDED', 'Suspendu'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='UPCOMING', max_length=32),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='final_decision',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='internship_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='internship_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='internship_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='specification_pdf',
            field=models.FileField(blank=True, null=True, upload_to='internships/specifications/'),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='subject_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_interns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InternDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONVENTION', 'Convention de stage'), ('INSURANCE', 'Assurance'), ('SCHOOL_CERT', 'Attestation de scolarité'), ('NDA', 'Accord de confidentialité'), ('OTHER', 'Autre document')], max_length=32)),
                ('file', models.FileField(upload_to='internships/documents/')),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.internprofile')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_intern_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('INITIAL', 'Évaluation initiale'), ('MIDTERM', 'Évaluation à mi-parcours'), ('FINAL', 'Évaluation finale')], max_length=32)),
                ('technical_skills', models.IntegerField(default=0)),
                ('autonomy', models.IntegerField(default=0)),
                ('communication', models.IntegerField(default=0)),
                ('teamwork', models.IntegerField(default=0)),
                ('deadline_respect', models.IntegerField(default=0)),
                ('work_quality', models.IntegerField(default=0)),
                ('professionalism', models.IntegerField(default=0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intern_evaluations', to=settings.AUTH_USER_MODEL)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='recruitment.internprofile')),
            ],
        ),
    ]
