# Generated by Django 5.2.16 on 2026-07-28 15:20
from django.db import migrations

def migrate_statuses(apps, schema_editor):
    Application = apps.get_model('recruitment', 'Application')
    ApplicationStatusHistory = apps.get_model('recruitment', 'ApplicationStatusHistory')

    # Update Application
    Application.objects.filter(status='SUBMITTED').update(status='RECEIVED')
    Application.objects.filter(status='INTERVIEW_SCHEDULED').update(status='INTERVIEW')
    Application.objects.filter(status='INTERVIEW_COMPLETED').update(status='INTERVIEW')
    Application.objects.filter(status='CANCELLED').update(status='ARCHIVED')

    # Update ApplicationStatusHistory
    ApplicationStatusHistory.objects.filter(from_status='SUBMITTED').update(from_status='RECEIVED')
    ApplicationStatusHistory.objects.filter(from_status='INTERVIEW_SCHEDULED').update(from_status='INTERVIEW')
    ApplicationStatusHistory.objects.filter(from_status='INTERVIEW_COMPLETED').update(from_status='INTERVIEW')
    ApplicationStatusHistory.objects.filter(from_status='CANCELLED').update(from_status='ARCHIVED')

    ApplicationStatusHistory.objects.filter(to_status='SUBMITTED').update(to_status='RECEIVED')
    ApplicationStatusHistory.objects.filter(to_status='INTERVIEW_SCHEDULED').update(to_status='INTERVIEW')
    ApplicationStatusHistory.objects.filter(to_status='INTERVIEW_COMPLETED').update(to_status='INTERVIEW')
    ApplicationStatusHistory.objects.filter(to_status='CANCELLED').update(to_status='ARCHIVED')

def reverse_migrate_statuses(apps, schema_editor):
    Application = apps.get_model('recruitment', 'Application')
    ApplicationStatusHistory = apps.get_model('recruitment', 'ApplicationStatusHistory')

    Application.objects.filter(status='RECEIVED').update(status='SUBMITTED')
    Application.objects.filter(status='INTERVIEW').update(status='INTERVIEW_SCHEDULED')
    Application.objects.filter(status='ARCHIVED').update(status='CANCELLED')

    ApplicationStatusHistory.objects.filter(from_status='RECEIVED').update(from_status='SUBMITTED')
    ApplicationStatusHistory.objects.filter(from_status='INTERVIEW').update(from_status='INTERVIEW_SCHEDULED')
    ApplicationStatusHistory.objects.filter(from_status='ARCHIVED').update(from_status='CANCELLED')

    ApplicationStatusHistory.objects.filter(to_status='RECEIVED').update(to_status='SUBMITTED')
    ApplicationStatusHistory.objects.filter(to_status='INTERVIEW').update(to_status='INTERVIEW_SCHEDULED')
    ApplicationStatusHistory.objects.filter(to_status='ARCHIVED').update(to_status='CANCELLED')


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_internprofile_business_unit_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_migrate_statuses),
    ]
