# Generated by Django 5.2.16 on 2026-07-31 09:26

import apps.recruitment.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_migrate_obsolete_application_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interndocument',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interndocument',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='interndocument',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interndocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='interndocument',
            name='file',
            field=models.FileField(upload_to=apps.recruitment.models.intern_document_upload_to),
        ),
        migrations.CreateModel(
            name='InternDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONVENTION', 'Convention de stage'), ('INSURANCE', 'Assurance'), ('SCHOOL_CERT', 'Attestation de scolarité'), ('NDA', 'Accord de confidentialité'), ('OTHER', 'Autre document')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intern_document_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='interndocument',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='recruitment.interndocumentrequirement'),
        ),
    ]
