# Generated by Django 5.2.16 on 2026-08-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_cvanalysis_applicationmatch'),
        ('trainings', '0006_daily_session_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill_gaps', models.JSONField(default=list)),
                ('explanation', models.TextField()),
                ('algorithm_version', models.CharField(default='skill-gap-v1', max_length=32)),
                ('human_decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_recommendations', to='recruitment.application')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_recommendations', to='trainings.training')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('application', 'training'), name='unique_application_training_recommendation')],
            },
        ),
    ]
