# Generated by Django 5.2.16 on 2026-08-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_intern_document_submission_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('PFA_INTERNSHIP', 'Stage PFA'), ('PFE_INTERNSHIP', 'Stage PFE'), ('HIRING', 'Candidature spontanée')], max_length=32),
        ),
        migrations.AlterField(
            model_name='offer',
            name='application_type',
            field=models.CharField(choices=[('PFA_INTERNSHIP', 'Stage PFA'), ('PFE_INTERNSHIP', 'Stage PFE'), ('HIRING', 'Candidature spontanée')], max_length=32, verbose_name="Type d'offre"),
        ),
    ]
