import { BreakpointObserver, BreakpointState } from '@angular/cdk/layout';
import { Component } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { Router, RouterLinkActive, provideRouter } from '@angular/router';
import { By } from '@angular/platform-browser';
import { BehaviorSubject, filter } from 'rxjs';
import { UserProfile } from '../../core/models/auth.models';
import { AuthService } from '../../core/services/auth.service';
import { MainLayoutComponent } from './main-layout.component';
@Component({standalone:true,template:'<h1>Candidatures chargées</h1>'}) class ApplicationsTestPage{}
describe('MainLayoutComponent',()=>{let fixture:ComponentFixture<MainLayoutComponent>;let component:MainLayoutComponent;let auth:jasmine.SpyObj<AuthService>&{currentUser$:BehaviorSubject<UserProfile|null>};let breakpoint:BehaviorSubject<BreakpointState>;const user:UserProfile={id:1,email:'hr@example.com',first_name:'Hiba',last_name:'Admin',full_name:'Hiba Admin',phone_number:'',role:'HR'};
beforeEach(async()=>{auth=Object.assign(jasmine.createSpyObj<AuthService>('AuthService',['ensureProfile','logout']),{currentUser$:new BehaviorSubject<UserProfile|null>(user)});auth.ensureProfile.and.returnValue(auth.currentUser$.pipe(filter((profile): profile is UserProfile=>profile !== null)));breakpoint=new BehaviorSubject<BreakpointState>({matches:false,breakpoints:{}});await TestBed.configureTestingModule({imports:[MainLayoutComponent],providers:[provideRouter([{path:'applications',component:ApplicationsTestPage}]),{provide:AuthService,useValue:auth},{provide:BreakpointObserver,useValue:{observe:()=>breakpoint.asObservable()}}]}).compileComponents();fixture=TestBed.createComponent(MainLayoutComponent);component=fixture.componentInstance;fixture.detectChanges();});
it('renders the premium sidebar navigation',()=>{expect(fixture.nativeElement.querySelector('.premium-sidebar')).not.toBeNull();expect(fixture.nativeElement.querySelector('img[alt="Finatech"]')).not.toBeNull();});
it('shows exactly one account control and no duplicate logout',()=>{expect(fixture.nativeElement.querySelectorAll('.account-trigger').length).toBe(1);});
it('keeps personal space on an internal router link',async()=>{(fixture.nativeElement.querySelector('.account-trigger') as HTMLButtonElement).click();fixture.detectChanges();await fixture.whenStable();const link=document.body.querySelector('a[href="/profile"]');expect(link).not.toBeNull();});
it('renders routed content after one navigation click',async()=>{const router=TestBed.inject(Router);const links=fixture.nativeElement.querySelectorAll('a[href="/applications"]');if(links.length > 0) { links[0].click(); await fixture.whenStable(); fixture.detectChanges(); expect(router.url).toBe('/applications'); expect(fixture.nativeElement.textContent).toContain('Candidatures chargées'); }});
it('delegates logout',()=>{component.logout();expect(auth.logout).toHaveBeenCalled();});
it('keeps the resolved identity while a transient null state is emitted',()=>{auth.currentUser$.next(null);fixture.detectChanges();expect(fixture.nativeElement.querySelector('.authenticated-theme')).not.toBeNull();});
it('configures active-route tracking on sidebar links',()=>{const activeLinks=fixture.debugElement.queryAll(By.directive(RouterLinkActive));expect(activeLinks.length).toBeGreaterThan(0);expect(fixture.nativeElement.querySelector('.nav-item')).not.toBeNull();});
it('renders a stable private layout for HR, candidate and employee roles',()=>{for(const role of ['HR','CANDIDATE','EMPLOYEE'] as const){auth.currentUser$.next({...user,role});fixture.detectChanges();expect(fixture.nativeElement.querySelector('.authenticated-theme')).not.toBeNull();expect(fixture.nativeElement.querySelector('.premium-sidebar')).not.toBeNull();}});
it('does not expose Business Units to candidates',()=>{auth.currentUser$.next({...user,role:'CANDIDATE'});fixture.detectChanges();expect(fixture.nativeElement.querySelector('.sidebar-nav')?.textContent).not.toContain('Business Units');});
it('shows only own-BU navigation without HR applications to BU managers',()=>{auth.currentUser$.next({...user,role:'BU_MANAGER'});fixture.detectChanges();const text=fixture.nativeElement.querySelector('.sidebar-nav')?.textContent;expect(text).toContain('Besoins de ma BU');expect(text).toContain('Membres de ma BU');expect(text).not.toContain('Business Units');expect(text).not.toContain('Candidatures');});
});
