# Generated by Django 5.2.16 on 2026-07-16 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_units', '0006_alter_businessunitneed_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('project_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('training_type', models.CharField(choices=[('INTERNAL', 'Interne'), ('CLIENT', 'Client'), ('TECHNICAL', 'Technique'), ('SOFT_SKILLS', 'Soft Skills'), ('CERTIFICATION', 'Certification'), ('E_LEARNING', 'E-Learning')], max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('objectives', models.TextField()),
                ('prerequisites', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(help_text='Durée en heures')),
                ('delivery_mode', models.CharField(choices=[('ON_SITE', 'Présentiel'), ('REMOTE', 'Distanciel'), ('HYBRID', 'Hybride'), ('E_LEARNING', 'E-Learning')], max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('associated_link', models.URLField(blank=True)),
                ('moodle_course_id', models.CharField(blank=True, max_length=100)),
                ('moodle_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='trainings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_trainings', to='business_units.businessunit')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to=settings.AUTH_USER_MODEL)),
                ('external_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_trainings', to='trainings.clientprofile')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('online_link', models.URLField(blank=True)),
                ('maximum_participants', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('OPEN', 'Ouverte'), ('FULL', 'Complète'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('external_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='trainings.clientprofile')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='trainings.training')),
            ],
        ),
    ]
