# Generated by Django 5.2.16 on 2026-07-16 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING_MANAGER', 'En attente du manager'), ('REJECTED_BY_MANAGER', 'Refusé par le manager'), ('PENDING_SUPER_ADMIN', 'En attente du Super Admin'), ('REJECTED_BY_SUPER_ADMIN', 'Refusé par le Super Admin'), ('APPROVED', 'Approuvée'), ('ENROLLED', 'Inscrit'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING_MANAGER', max_length=50)),
                ('manager_decision', models.CharField(blank=True, choices=[('PENDING_MANAGER', 'En attente du manager'), ('REJECTED_BY_MANAGER', 'Refusé par le manager'), ('PENDING_SUPER_ADMIN', 'En attente du Super Admin'), ('REJECTED_BY_SUPER_ADMIN', 'Refusé par le Super Admin'), ('APPROVED', 'Approuvée'), ('ENROLLED', 'Inscrit'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], max_length=50)),
                ('manager_comment', models.TextField(blank=True)),
                ('manager_decided_at', models.DateTimeField(blank=True, null=True)),
                ('super_admin_decision', models.CharField(blank=True, choices=[('PENDING_MANAGER', 'En attente du manager'), ('REJECTED_BY_MANAGER', 'Refusé par le manager'), ('PENDING_SUPER_ADMIN', 'En attente du Super Admin'), ('REJECTED_BY_SUPER_ADMIN', 'Refusé par le Super Admin'), ('APPROVED', 'Approuvée'), ('ENROLLED', 'Inscrit'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], max_length=50)),
                ('super_admin_comment', models.TextField(blank=True)),
                ('super_admin_decided_at', models.DateTimeField(blank=True, null=True)),
                ('final_status', models.CharField(choices=[('PENDING_MANAGER', 'En attente du manager'), ('REJECTED_BY_MANAGER', 'Refusé par le manager'), ('PENDING_SUPER_ADMIN', 'En attente du Super Admin'), ('REJECTED_BY_SUPER_ADMIN', 'Refusé par le Super Admin'), ('APPROVED', 'Approuvée'), ('ENROLLED', 'Inscrit'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING_MANAGER', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_enrollments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='trainings.trainingsession')),
                ('super_admin_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_managed_enrollments', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='trainings.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING_MANAGER', 'En attente du manager'), ('REJECTED_BY_MANAGER', 'Refusé par le manager'), ('PENDING_SUPER_ADMIN', 'En attente du Super Admin'), ('REJECTED_BY_SUPER_ADMIN', 'Refusé par le Super Admin'), ('APPROVED', 'Approuvée'), ('ENROLLED', 'Inscrit'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], max_length=50)),
                ('new_status', models.CharField(choices=[('PENDING_MANAGER', 'En attente du manager'), ('REJECTED_BY_MANAGER', 'Refusé par le manager'), ('PENDING_SUPER_ADMIN', 'En attente du Super Admin'), ('REJECTED_BY_SUPER_ADMIN', 'Refusé par le Super Admin'), ('APPROVED', 'Approuvée'), ('ENROLLED', 'Inscrit'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='trainings.trainingenrollment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trainingenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REJECTED_BY_MANAGER', 'REJECTED_BY_SUPER_ADMIN', 'CANCELLED']), _negated=True), fields=('user', 'session'), name='unique_active_enrollment'),
        ),
    ]
