# Generated by Django 5.2.16 on 2026-07-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_sessionattendance_attendancehistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingenrollment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'ordering': ['-created_at']},
        ),
    ]
