# Generated by Django 5.2.16 on 2026-07-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_training_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='moodle_course_id',
        ),
        migrations.RemoveField(
            model_name='training',
            name='moodle_link',
        ),
    ]
